// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWOI15yvR377a-fJvNXGIXe6jWdsyMHs',
    appId: '1:3340142064:web:3bd4c1a4afb705f9a30935',
    messagingSenderId: '3340142064',
    projectId: 'jasproj-8f9b3',
    authDomain: 'jasproj-8f9b3.firebaseapp.com',
    storageBucket: 'jasproj-8f9b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ8jE5OO-oxWW6DvKmpTxZr8BY_DXLjr8',
    appId: '1:3340142064:android:4ca3dc3fc2c215dda30935',
    messagingSenderId: '3340142064',
    projectId: 'jasproj-8f9b3',
    storageBucket: 'jasproj-8f9b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8oEnKAqaT_-umyYCagOHmvltE2nIAsQc',
    appId: '1:3340142064:ios:bcf7bc2df671a51da30935',
    messagingSenderId: '3340142064',
    projectId: 'jasproj-8f9b3',
    storageBucket: 'jasproj-8f9b3.firebasestorage.app',
    iosBundleId: 'com.fnine.jasserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8oEnKAqaT_-umyYCagOHmvltE2nIAsQc',
    appId: '1:3340142064:ios:bcf7bc2df671a51da30935',
    messagingSenderId: '3340142064',
    projectId: 'jasproj-8f9b3',
    storageBucket: 'jasproj-8f9b3.firebasestorage.app',
    iosBundleId: 'com.fnine.jasserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxWOI15yvR377a-fJvNXGIXe6jWdsyMHs',
    appId: '1:3340142064:web:ec28d6555193c1aba30935',
    messagingSenderId: '3340142064',
    projectId: 'jasproj-8f9b3',
    authDomain: 'jasproj-8f9b3.firebaseapp.com',
    storageBucket: 'jasproj-8f9b3.firebasestorage.app',
  );
}
